### ISSUE TITLE
Where is the top directory of this docker image?

### ISSUE THREAD

**Issue by seonghobae** [kuborgh/docker-php-5.2#2]
Hello,

I can not find where the top directory of this docker image, especially 'project' directory is. 
When I try to run this image, apache was hanging with the error message, could not find '/project' directory.

I'm a newbie in Docker, so, please let me know how can I implement my project files with this docker image.

Best, 
Seongho

**Comment by hgiesenow** [comment]
The folder `/project` is right. You need to bind-mount your source code into that directory. I suggest using docker-compose for this purpose (https://docs.docker.com/compose/compose-file/#volumes).

**Comment by seonghobae** [comment]
Thanks for the reply, so How about Like this?

```docker
version: "3.2"
services:
  web:
    image: kuborgh/php-5.2
    volumes:
      - type: volume
        source: mydata
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: ./project
        target: /opt/app/project

volumes:
  mydata:
```

**Comment by MilesHart** [comment]
I'm struggling with this, I'm a noobie (isn't everyone to a degree?).

This will get you started. (Windows volume path)

docker run --rm -d -p 80:80/tcp -v c:\docker\phpinfo:/project kuborgh/php-5.2:latest

**Comment by m1st3rl1** [comment]
hey, we no longer support and upgrade this one. Please use an official php image.
